spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
          - Path=/api/v2/productos/**
        filters:
          - StripPrefix=3
          - name: Ejemplo
            args:
              mensaje: Hola mi mensaje personalizado
              cookieNombre: marca
              cookieValor: Xiaomi
      - id: servicio-items
        uri: lb://servicio-items
        predicates:
          - Path=/api/v2/items/**
        filters:
          - StripPrefix=3